(function(){'use strict';function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function q(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function fa(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var ha="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;
if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function na(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.B=b.prototype}q("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});q("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var t=this||self;function oa(a){a:{var b=["CLOSURE_FLAGS"];for(var c=t,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}a=b&&b[a];return null!=a?a:!1};var pa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var qa=oa(610401301),ra=oa(188588736);var u,sa=t.navigator;u=sa?sa.userAgentData||null:null;function wa(a){return qa?u?u.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function w(a){var b;a:{if(b=t.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function x(){return qa?!!u&&0<u.brands.length:!1}function xa(){return x()?wa("Chromium"):(w("Chrome")||w("CriOS"))&&!(x()?0:w("Edge"))||w("Silk")};var ya=x()?!1:w("Trident")||w("MSIE");function za(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};function Aa(a){a=void 0===a?document:a;return a.createElement("img")};function Ba(a,b,c){var d=!1;d=void 0===d?!1:d;a.google_image_requests||(a.google_image_requests=[]);var e=Aa(a.document);if(c){var f=function(){if(c){var g=a.google_image_requests,h=pa(g,e);0<=h&&Array.prototype.splice.call(g,h,1)}e.removeEventListener&&e.removeEventListener("load",f,!1);e.removeEventListener&&e.removeEventListener("error",f,!1)};e.addEventListener&&e.addEventListener("load",f,!1);e.addEventListener&&e.addEventListener("error",f,!1)}d&&(e.attributionSrc="");e.src=b;a.google_image_requests.push(e)}
;function Ca(a){t.setTimeout(function(){throw a;},0)};!w("Android")||xa();xa();w("Safari")&&(xa()||(x()?0:w("Coast"))||(x()?0:w("Opera"))||(x()?0:w("Edge"))||(x()?wa("Microsoft Edge"):w("Edg/"))||x()&&wa("Opera"));var Da={},y=null;
function Ea(a){var b;void 0===b&&(b=0);if(!y){y={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Da[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===y[h]&&(y[h]=g)}}}b=Da[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var l=a[f],k=a[f+1];h=a[f+2];g=b[l>>2];l=b[(l&3)<<4|k>>4];k=b[(k&15)<<2|h>>6];h=b[h&63];c[e++]=g+l+k+h}g=0;h=d;switch(a.length-f){case 2:g=
a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")};var Fa,Ga="function"===typeof String.prototype.u,Ha="undefined"!==typeof TextEncoder;var Ia="undefined"!==typeof Uint8Array,Ja=!ya&&"function"===typeof btoa;var Ka=0,La=0,Ma;function Na(){this.g=[]}Na.prototype.length=function(){return this.g.length};Na.prototype.end=function(){var a=this.g;this.g=[];return a};function z(a,b){for(;127<b;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function Oa(a,b){if(0<=b)z(a,b);else{for(var c=0;9>c;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function Pa(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function Qa(){this.j=[];this.i=0;this.g=new Na}function B(a,b){0!==b.length&&(a.j.push(b),a.i+=b.length)};function C(a,b){this.g=a;this.o=b};function D(a){return Array.prototype.slice.call(a)};function Ra(a){return"function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():a}var E=Ra(),Sa=Ra("2ex");var Ta=E?function(a,b){a[E]|=b}:function(a,b){void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})},Ua=E?function(a,b){a[E]&=~b}:function(a,b){void 0!==a.g&&(a.g&=~b)};function F(a,b,c){return c?a|b:a&~b}
var G=E?function(a){return a[E]|0}:function(a){return a.g|0},H=E?function(a){return a[E]}:function(a){return a.g},I=E?function(a,b){a[E]=b;return a}:function(a,b){void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a};function Va(a,b){I(b,(a|0)&-14591)}function Wa(a,b){I(b,(a|34)&-14557)}function Xa(a){a=a>>14&1023;return 0===a?536870912:a};var J={},Ya={};function Za(a){return!(!a||"object"!==typeof a||a.g!==Ya)}function $a(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}function K(a,b,c){if(!Array.isArray(a)||a.length)return!1;var d=G(a);if(d&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;I(a,d|1);return!0}var ab,bb=[];I(bb,55);ab=Object.freeze(bb);function L(a){if(a&2)throw Error();}Object.freeze(new function(){});Object.freeze(new function(){});var cb;function db(a){a=Error(a);za(a,"warning");return a};function eb(a){if(!Number.isFinite(a))throw db("enum");return a|0}function fb(a){if("number"!==typeof a)throw db("int32");if(!Number.isFinite(a))throw db("int32");return a|0}function gb(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return Number.isFinite(a)?a|0:void 0}function M(a){if(null!=a&&"string"!==typeof a)throw Error();return a};var N,hb,ib;function kb(a){switch(typeof a){case "boolean":return hb||(hb=[0,void 0,!0]);case "number":return 0<a?void 0:0===a?ib||(ib=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}
function P(a,b,c){null==a&&(a=N);N=void 0;if(null==a){var d=96;c?(a=[c],d|=512):a=[];b&&(d=d&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");d=G(a);if(d&2048)throw Error("farr");if(d&64)return a;d|=64;if(c&&(d|=512,c!==a[0]))throw Error("mid");a:{c=a;var e=c.length;if(e){var f=e-1;if($a(c[f])){d|=256;b=f-(+!!(d&512)-1);if(1024<=b)throw Error("pvtlmt");d=d&-16760833|(b&1023)<<14;break a}}if(b){b=Math.max(b,e-(+!!(d&512)-1));if(1024<b)throw Error("spvt");d=d&-16760833|(b&1023)<<
14}}}I(a,d);return a};function lb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(K(a,void 0,0))return}else if(Ia&&null!=a&&a instanceof Uint8Array){if(Ja){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else a=Ea(a);return a}}return a};function mb(a,b,c){a=D(a);var d=a.length,e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var f in e)b[f]=c(e[f])}return a}function nb(a,b,c,d,e){if(null!=a){if(Array.isArray(a))a=K(a,void 0,0)?void 0:e&&G(a)&2?a:ob(a,b,c,void 0!==d,e);else if($a(a)){var f={},g;for(g in a)f[g]=nb(a[g],b,c,d,e);a=f}else a=b(a,d);return a}}function ob(a,b,c,d,e){var f=d||c?G(a):0;d=d?!!(f&32):void 0;a=D(a);for(var g=0;g<a.length;g++)a[g]=nb(a[g],b,c,d,e);c&&c(f,a);return a}
function pb(a){return a.l===J?a.toJSON():lb(a)};function qb(a,b,c){c=void 0===c?Wa:c;if(null!=a){if(Ia&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=G(a);if(d&2)return a;b&&(b=0===d||!!(d&32)&&!(d&64||!(d&16)));return b?I(a,(d|34)&-12293):ob(a,qb,d&4?Wa:c,!0,!0)}a.l===J&&(c=a.h,d=H(c),a=d&2?a:rb(a,c,d,!0));return a}}function rb(a,b,c,d){a=a.constructor;N=b=sb(b,c,d);b=new a(b);N=void 0;return b}function sb(a,b,c){var d=c||b&2?Wa:Va,e=!!(b&32);a=mb(a,b,function(f){return qb(f,e,d)});Ta(a,32|(c?2:0));return a};function tb(a,b,c,d){b=d+(+!!(b&512)-1);if(!(0>b||b>=a.length||b>=c))return a[b]}function ub(a,b,c,d){if(-1===c)return null;var e=Xa(b);if(c>=e){if(b&256)return a[a.length-1][c]}else{var f=a.length;if(d&&b&256&&(d=a[f-1][c],null!=d)){if(tb(a,b,e,c)&&null!=Sa){var g;a=null!=(g=cb)?g:cb={};g=a[Sa]||0;4<=g||(a[Sa]=g+1,g=Error(),za(g,"incident"),Ca(g))}return d}return tb(a,b,e,c)}}function Q(a,b,c){a=a.h;var d=H(a);L(d);R(a,d,b,c)}
function R(a,b,c,d,e){var f=Xa(b);if(c>=f||e){var g=b;if(b&256)e=a[a.length-1];else{if(null==d)return g;e=a[f+(+!!(b&512)-1)]={};g|=256}e[c]=d;c<f&&(a[c+(+!!(b&512)-1)]=void 0);g!==b&&I(a,g);return g}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}function vb(a){return!!(2&a)&&!!(4&a)||!!(2048&a)}
function S(a,b,c,d){a=a.h;var e=H(a);L(e);for(var f=e,g=0,h=0;h<c.length;h++){var l=c[h];null!=ub(a,f,l)&&(0!==g&&(f=R(a,f,g)),g=l)}(c=g)&&c!==b&&null!=d&&(e=R(a,e,c));R(a,e,b,d)}
function wb(a,b,c,d,e,f,g){var h=!!(2&b),l=h?1:2;f=!!f;g&&(g=!h);h=ub(a,b,d,e);h=Array.isArray(h)?h:ab;var k=G(h),n=!!(4&k);if(!n){var m=k;0===m&&(m=T(m,b));m=F(m,1,!0);k=h;var p=b,A=!!(2&m);A&&(p=F(p,2,!0));for(var ta=!A,ua=!0,Z=0,va=0;Z<k.length;Z++){var v=k[Z];var aa=c;if(null==v||"object"!==typeof v||v.l!==J)if(Array.isArray(v)){var jb=G(v),O=jb;0===O&&(O|=p&32);O|=p&2;O!==jb&&I(v,O);v=new aa(v)}else v=void 0;v instanceof c&&(A||(aa=!!(G(v.h)&2),ta&&(ta=!aa),ua&&(ua=aa)),k[va++]=v)}va<Z&&(k.length=
va);m=F(m,4,!0);m=F(m,16,ua);m=F(m,8,ta);I(k,m);A&&Object.freeze(k);k=m}if(g&&!(8&k||!h.length&&(1===l||4===l&&32&k))){vb(k)&&(h=D(h),k=T(k,b),b=R(a,b,d,h,e));c=h;g=k;for(k=0;k<c.length;k++)m=c[k],p=m.h,A=H(p),p=A&2?rb(m,p,A,!1):m,m!==p&&(c[k]=p);g=F(g,8,!0);g=F(g,16,!c.length);I(c,g);k=g}vb(k)||(c=k,(g=1===l||4===l&&!!(32&k))?(m=!!(32&k),k=F(k,!h.length||16&k&&(!n||m)?2:2048,!0)):k=xb(k,b,f),k!==c&&I(h,k),g&&Object.freeze(h));2===l&&vb(k)&&(h=D(h),k=T(k,b),k=xb(k,b,f),I(h,k),R(a,b,d,h,e));return h}
function yb(a,b){a=a.h;var c=H(a);return wb(a,c,zb,b,void 0,!1,!(2&c))}function Ab(a,b,c){var d=a.h,e=H(d);L(e);if(null==c)return R(d,e,b),a;for(var f=G(c),g=f,h=!!(2&f)||!!(2048&f),l=h||Object.isFrozen(c),k=!0,n=!0,m=0;m<c.length;m++){var p=c[m];h||(p=!!(G(p.h)&2),k&&(k=!p),n&&(n=p))}h||(f=F(f,5,!0),f=F(f,8,k),f=F(f,16,n));l&&f!==g&&(c=D(c),g=0,f=T(f,e),f=xb(f,e,!0));f!==g&&I(c,f);R(d,e,b,c);return a}function T(a,b){a=F(a,2,!!(2&b));a=F(a,32,!0);return a=F(a,2048,!1)}
function xb(a,b,c){32&b&&c||(a=F(a,32,!1));return a};function U(a,b,c){this.h=P(a,b,c)}U.prototype.toJSON=function(){return Bb(this,ob(this.h,pb,void 0,void 0,!1),!0)};U.prototype.l=J;U.prototype.toString=function(){return Bb(this,this.h,!1).toString()};
function Bb(a,b,c){var d=ra?void 0:a.constructor.m;var e=H(c?a.h:b);a=b.length;if(!a)return b;var f;if($a(c=b[a-1])){a:{var g=c;var h={},l=!1,k;for(k in g){var n=g[k];if(Array.isArray(n)){var m=n;if(K(n,d,+k)||Za(n)&&0===n.size)n=null;n!=m&&(l=!0)}null!=n?h[k]=n:l=!0}if(l){for(var p in h){g=h;break a}g=null}}g!=c&&(f=!0);a--}for(k=+!!(e&512)-1;0<a;a--){p=a-1;c=b[p];p-=k;if(!(null==c||K(c,d,p)||Za(c)&&0===c.size))break;var A=!0}if(!f&&!A)return b;b=Array.prototype.slice.call(b,0,a);g&&b.push(g);return b}
;var Cb=Symbol();function Db(a,b,c){a[b]=c}var Eb=Symbol();function Fb(a){var b=a[Eb];if(!b){var c=Gb(a);b=function(d,e){return Hb(d,e,c)};a[Eb]=b}return b}var Ib=Symbol();function Jb(a){return a.g}function Kb(a,b){var c,d,e=a.g;return function(f,g,h){return e(f,g,h,d||(d=Gb(b).g),c||(c=Fb(b)))}}
function Gb(a){var b=a[Ib];if(b)return b;b=a[Ib]={};var c=Jb,d=Kb;var e=void 0===e?Db:e;b.g=kb(a[0]);var f=0,g=a[++f];g&&g.constructor===Object&&(b.s=g,g=a[++f],"function"===typeof g&&(b.j=g,b.i=a[++f],g=a[++f]));for(var h={};Array.isArray(g)&&"number"===typeof g[0]&&0<g[0];){for(var l=0;l<g.length;l++)h[g[l]]=g;g=a[++f]}for(l=1;void 0!==g;){"number"===typeof g&&(l+=g,g=a[++f]);var k=void 0;if(g instanceof C)var n=g;else n=Lb,f--;if(n.o){g=a[++f];k=a;var m=f;"function"==typeof g&&(g=g(),k[m]=g);k=
g}g=a[++f];m=l+1;"number"===typeof g&&0>g&&(m-=g,g=a[++f]);for(;l<m;l++){var p=h[l];e(b,l,k?d(n,k,p):c(n,p))}}Mb in a&&Cb in a&&Ib in a&&(a.length=0);return b}var Mb=Symbol();function Nb(a,b){var c=a[b];if(c)return c;if(c=a.s)if(c=c[b]){c=Array.isArray(c)?c[0]instanceof C?c:[Ob,c]:[c,void 0];var d=c[0].g;if(c=c[1]){var e=Fb(c),f=Gb(c).g;c=(c=a.i)?c(f,e):function(g,h,l){return d(g,h,l,f,e)}}else c=d;return a[b]=c}}
function Hb(a,b,c){for(var d=H(a),e=+!!(d&512)-1,f=a.length,g=f+(d&256?-1:0),h=d&512?1:0;h<g;h++){var l=a[h];if(null!=l){var k=h-e,n=Nb(c,k);n&&n(b,l,k)}}if(d&256){a=a[f-1];for(var m in a)d=+m,Number.isNaN(d)||(e=a[m],null!=e&&(f=Nb(c,d))&&f(b,e,d))}}
function Pb(a,b,c){b=null==b||"string"===typeof b?b:void 0;if(null!=b){var d=!1;d=void 0===d?!1:d;if(Ha){if(d&&(Ga?!b.u():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b)))throw Error("Found an unpaired surrogate");b=(Fa||(Fa=new TextEncoder)).encode(b)}else{for(var e=0,f=new Uint8Array(3*b.length),g=0;g<b.length;g++){var h=b.charCodeAt(g);if(128>h)f[e++]=h;else{if(2048>h)f[e++]=h>>6|192;else{if(55296<=h&&57343>=h){if(56319>=h&&g<b.length){var l=b.charCodeAt(++g);
if(56320<=l&&57343>=l){h=1024*(h-55296)+l-56320+65536;f[e++]=h>>18|240;f[e++]=h>>12&63|128;f[e++]=h>>6&63|128;f[e++]=h&63|128;continue}else g--}if(d)throw Error("Found an unpaired surrogate");h=65533}f[e++]=h>>12|224;f[e++]=h>>6&63|128}f[e++]=h&63|128}}b=e===f.length?f:f.subarray(0,e)}z(a.g,8*c+2);z(a.g,b.length);B(a,a.g.end());B(a,b)}}
function Qb(a,b,c,d,e){b=b instanceof U?b.h:Array.isArray(b)?P(b,d[0],d[1]):void 0;if(null!=b){z(a.g,8*c+2);c=a.g.end();B(a,c);c.push(a.i);e(b,a);e=c.pop();for(e=a.i+a.g.length()-e;127<e;)c.push(e&127|128),e>>>=7,a.i++;c.push(e);a.i++}}
var Rb=new C(function(a,b,c){b=null==b||"number"===typeof b?b:"NaN"===b||"Infinity"===b||"-Infinity"===b?Number(b):void 0;null!=b&&(z(a.g,8*c+1),a=a.g,c=Ma||(Ma=new DataView(new ArrayBuffer(8))),c.setFloat64(0,+b,!0),Ka=c.getUint32(0,!0),La=c.getUint32(4,!0),Pa(a,Ka),Pa(a,La))},!1),Sb=new C(function(a,b,c){b=gb(b);null!=b&&null!=b&&(z(a.g,8*c),Oa(a.g,b))},!1),Tb=new C(Pb,!1),Ub=new C(Pb,!1),Ob=new C(Qb,!0),Lb=new C(Qb,!0),Vb;
Vb=new C(function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Qb(a,b[f],c,d,e)},!0);var Wb=new C(function(a,b,c){b=gb(b);null!=b&&(b=parseInt(b,10),z(a.g,8*c),Oa(a.g,b))},!1);function zb(a){this.h=P(a)}na(zb,U);var Xb=[1,2,3],Yb=[4,5],Zb=[0,Xb,Yb,Wb,-1,Ub,Rb,Ub,Sb];function $b(a){this.h=P(a)}na($b,U);$b.m=[1];$b.prototype.g=function(a){return function(){var b=new Qa;Hb(this.h,b,Gb(a));B(b,b.g.end());for(var c=new Uint8Array(b.i),d=b.j,e=d.length,f=0,g=0;g<e;g++){var h=d[g];c.set(h,f);f+=h.length}b.j=[c];return c}}([0,Vb,Zb,Tb,1,Tb,Sb]);function ac(a){this.h=P(a)}na(ac,U);ac.prototype.setData=function(a,b){var c=zb,d=this.h,e=H(d);L(e);d=wb(d,e,c,2,!1,!0);b=null!=b?b:new c;if("number"!==typeof a||0>a||a>d.length)throw Error();void 0!=a?d.splice(a,1,b):d.push(b);G(b.h)&2?Ua(d,8):Ua(d,16);return this};ac.m=[1,2];function bc(){this.data=[];this.i=[];this.g=[]}bc.prototype.setData=function(a,b,c){this.g.includes(c)&&this.data.push({key:a,value:b,channel:c})};function cc(a){return a.data.some(function(b){return 1===b.channel})}bc.prototype.setAttribute=function(a,b){this.i.push({key:a,value:b})};
function dc(a,b,c,d){var e=new zb;"string"===typeof a?S(e,3,Xb,M(a)):d?S(e,1,Xb,null==a?a:eb(a)):S(e,2,Xb,null==a?a:eb(a));if("number"===typeof b){if(null==b)a=b;else{if("number"!==typeof b)throw Error("Value of float/double field must be a number, found "+typeof b+": "+b);a=b}S(e,4,Yb,a)}else S(e,5,Yb,M(b));c&&Q(e,6,null==c?c:fb(c));return e};function V(){this.g=new bc;this.j=Date.now()}
V.prototype.init=function(a,b,c,d,e,f){var g=this;this.g.g.push.apply(this.g.g,b instanceof Array?b:fa(r(b)));this.A=a;this.i=e;this.v=c;if(d)for(a=r(d),b=a.next();!b.done;b=a.next())c=r(b.value),b=c.next().value,c=c.next().value,this.g.setAttribute(b,c);if(f){f=r(f);for(a=f.next();!a.done;a=f.next())c=r(a.value),a=c.next().value,b=c.next().value,c=c.next().value,this.setData(a,b,c);"complete"===document.readyState?this.send():window.addEventListener("load",function(){g.send()})}};
V.prototype.getBaseTime=function(){return this.j};V.prototype.setData=function(a,b,c){this.g.setData(a,b,c)};V.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};V.prototype.send=function(a){var b=this,c=cc(this.g)?0:100;a=null!=a?a:c;0<a?setTimeout(function(){return void ec(b)},a):ec(this)};
function ec(a){if(0<a.g.data.length){var b=a.A,c=a.i,d=a.v,e=a.g,f=[];var g=r(e.i);for(var h=g.next();!h.done;h=g.next())h=h.value,f.push(dc(h.key,h.value,void 0,!0));g=[];e=r(e.data);for(h=e.next();!h.done;h=e.next())h=h.value,g.push(dc(h.key,h.value,h.channel,!1));e=new ac;f=Ab(e,1,f);g=Ab(f,2,g);f=new $b;g=yb(g,1).concat(yb(g,2));f=Ab(f,1,g);b&&Q(f,2,M(b));d&&Q(f,4,M(d));c&&Q(f,5,null==c?c:fb(c));b="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+Ea(f.g()).replace(/\//g,"_").replace(/\+/g,
"-");c=window;var l=void 0===l?!1:l;if(d=c.navigator)d=c.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&c.navigator.sendBeacon?c.navigator.sendBeacon(b):Ba(c,b,void 0===l?!1:l);a.g.data=[]}}if(!window.mys||!window.mys.pingback){var fc=new V,W=["mys","pingback"],X=t;W[0]in X||"undefined"==typeof X.execScript||X.execScript("var "+W[0]);for(var Y;W.length&&(Y=W.shift());)W.length||void 0===fc?X[Y]&&X[Y]!==Object.prototype[Y]?X=X[Y]:X=X[Y]={}:X[Y]=fc};}).call(this);
